name: escala_mobile
description: "Aplicativo de Escalas e Permutas para Defesa Civil Maricá."
publish_to: 'none'

version: 1.0.0+1

environment:
  # Compatível com Flutter 3.22.2
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Versões estáveis e compatíveis
  http: ^1.2.0
  provider: ^6.1.2
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8
  # A versão estável mais recente do intl
  intl: 0.20.2
  logger: ^2.3.0
  pdf: ^3.10.8
  path_provider: ^2.1.3
  open_file: ^3.3.2
  flutter_local_notifications: ^17.1.2
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.2
  shared_preferences: ^2.2.3
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.16.8
  webview_flutter_wkwebview: ^3.12.0
  webview_flutter_web: ^0.2.3+4
  js: ^0.7.1
  syncfusion_flutter_datagrid: ^30.1.38
  syncfusion_flutter_core: ^30.1.38

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/


flutter_launcher_icons:
  # --- Configuração Geral ---
  # Este é o caminho para a sua imagem MESTRE.
  # Verifique se o arquivo existe em: assets/icon/icone_defesacivil_1024.png
  image_path: "assets/icon/icone_defesacivil_1024.png"

  # --- Configuração para Android e iOS ---
  android: true
  ios: true
  remove_alpha_ios: true

  # --- Configuração para Web ---
  web:
    generate: true
    # A cor de fundo que aparecerá na tela de splash do PWA
    background_color: "#0175C2" 
    # A cor do tema da barra do navegador no PWA
    theme_color: "#0175C2"
    