name: escala_mobile
description: "Aplicativo de Escalas e Permutas para Defesa Civil Maricá."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.1.2
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  logger: ^2.4.0
  pdf: ^3.11.0
  path_provider: ^2.1.5
  open_file: ^3.5.10
  flutter_local_notifications: ^17.2.3
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/SalvamentoMaritimo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/