name: escala_mobile
description: "Aplicativo de Escalas e Permutas para Defesa Civil Maricá."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.0.5
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  logger: ^2.0.2
  pdf: ^3.10.8
  path_provider: ^2.1.3
  open_file: ^3.3.2
  flutter_local_notifications: ^17.0.0
  firebase_core: ^2.24.2  # Atualizado para a versão mais recente
  firebase_messaging: ^14.7.10
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/SalvamentoMaritimo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/