platform :ios, '12.0'

# Inclui o podhelper.rb diretamente
require_relative './Flutter/podhelper'

target 'Runner' do
  use_modular_headers!

  # Inclui Firebase Messaging
  pod 'Firebase/Messaging'

  # Instala os pods do Flutter
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_post_install(installer) if defined?(flutter_post_install)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
      config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
    end
  end
end
