# Autogenerated file by Flutter. Do not edit.
# Minimum iOS platform version supported by Flutter
def flutter_ios_min_version
    '12.0'
  end
  
  # Installs all Flutter pods for the specified target
  def flutter_install_all_ios_pods(flutter_application_path)
    raise "Please specify the flutter_application_path" unless flutter_application_path
  
    # Ensure minimum iOS version
    platform :ios, flutter_ios_min_version
  
    # Include Flutter engine and plugins
    eval(File.read(File.join(flutter_application_path, 'ios', 'Flutter', 'Generated.xcconfig')), binding)
  
    # Add Flutter pod
    pod 'Flutter', :path => File.join(flutter_application_path, '.ios', 'Flutter', 'engine')
    pod 'FlutterPluginRegistrant', :path => File.join(flutter_application_path, '.ios', 'Flutter', 'FlutterPluginRegistrant')
  
    # Add plugin pods
    Dir[File.join(flutter_application_path, '.ios', 'Flutter', 'plugins', '*')].each do |plugin|
      podspec = File.join(plugin, "#{File.basename(plugin)}.podspec")
      if File.exist?(podspec)
        pod File.basename(plugin), :path => plugin
      end
    end
  end
  
  # Post-install configurations for Flutter
  def flutter_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = flutter_ios_min_version
      end
    end
  end